# Generated by Django 4.1.5 on 2023-01-24 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=200)),
                ('correct', models.CharField(max_length=200)),
                ('incorrect', models.CharField(max_length=200)),
                ('percentage', models.CharField(max_length=200)),
                ('quiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.questionmodel')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Quiz_Leaderboard',
            },
        ),
    ]
