# Generated by Django 4.1.5 on 2023-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_leaderboard_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
